[package]
name = "sedenion-api"
version = "0.0.0"
edition = "2021"

[dependencies]
pretty_env_logger = "0.5.0"
log = "0.4"
thruster = { version = "1.3.0", features = ["hyper_server"] }
tokio = { version = "1.6", features = ["rt", "rt-multi-thread", "macros"] }